name: EAS continuous deploy

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup node
      uses: actions/setup-nodev3

    - name: Setup cache
      uses: actions/cache@v4
      with:
        path: "**/node_modules"
        key: ${{runner.os}}-modules-${{hashFiles('**/yarn.lock')}}

    - name: Install dependencies
      run: yarn
      shell: bash

    - name: Setup EAS
      uses: expo/expo-github-action@v8
      with:
        eas-version: latest
        token: ${{secrets.EXPO_TOKEN}}

    - name: Update EAS
      run: expo update eas
